version: '3.1'

services:
  db:
    image: postgres:11.22-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env

  orchestrator:
    build: 
      context: ./m_orchestrator
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
        - db
        - redis

  worker:
    build: 
      context: ./m_worker
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
        - orchestrator

  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
